apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: {{ .Values.vote.image }}
          command: ["python", "app.py"]
          env:
            - name: REDIS_HOST
              value: {{ .Values.vote.env.REDIS_HOST }}
          ports:
            - containerPort: 80
