global:
  security:
    allowInsecureImages: false
  redis:
    password: ""

iimage:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.4.2-debian-12-r6

pdb:
  create: true

usePassword: false
password: ""

service:
  ports:
    redis: 6379
  type: ClusterIP

persistence:
  enabled: true
  path: /bitnami/redis/data
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 8Gi

persistentVolumeClaimRetentionPolicy:
  enabled: false
  whenScaled: Delete
  whenDeleted: Delete

redis:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

  podManagementPolicy: Parallel
  automountServiceAccountToken: false
  hostNetwork: false

  containerPorts:
    redis: 6379
    bus: 16379

  resourcesPreset: "nano"
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi

  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  startupprobe:
    enabled: false
    path: /
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  podAfinityPreset: soft

metrics:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/redis-exporter
      tag: 1.67.0-debian-12-r7
      digest: ""
      pullPolicy: IfNotPresent
    resourcesPreset: "nano"
    ## resources:
    ##   requests:
    ##     cpu: 2
    ##     memory: 512Mi
    ##   limits:
    ##     cpu: 3
    ##     memory: 1024Mi

    serviceMonitor:
      enabled: true
      namespace: monitoring
    service:
      type: ClusterIP
      ports:
        http: 9121